#!/bin/sh

check() {
    if [ $? -ne 0 ]; then
        echo "[FAILURE]"
        exit 1
    fi
}

echo "[XTELEPATCH]"
echo "<MAKE SURE YOU HAVE EXECUTED {./prepare} BEFORE {./execute}>"
. run/setup.sh
check
./run/build.sh
check
./run/patch.sh
check
./run/install.sh
check
echo "[EXIT]"
